### ISSUE TITLE
US ID11: As a player, I want to finish a game after a certain number of questions and get the final ranking list in order to see how well I performed after all questions have been answered.

### ISSUE THREAD

**Issue by a1ps** [sopra-fs23-group-12/4Bubbles_Server#10]
- [x] sopra-fs23-group-12/4Bubbles_Client#39

**AC**
- [x] - [ ] The game ends when a given number of question rounds have passed. 

- [x] sopra-fs23-group-12/4Bubbles_Client#34

- [ ] The option to start a new game is presented to the players. Clicking this starts a game with the same members. 

- [x] The other option would be to return to the game room.

- [ ] Optionally the table can be shared.

**Comment by Bluee1Bird** [comment]
proposed additional tasks:
Backend:
 change the first task to be specifically about the backend tracking the #questions

**Comment by a1ps** [comment]
Optional würdi hier au wegloh
