### ISSUE TITLE
US ID15: As a player I want to stay informed about the question and how much time remains to answer in order to be able to not miss the answer deadline.

### ISSUE THREAD

**Issue by a1ps** [sopra-fs23-group-12/4Bubbles_Server#11]
- [x] While the player can answer, the question remains displayed at the top of the screen. 

- [x] While the voting is active, the player can select their answer by clicking on an answer bubble.

- [x] After a limited number of seconds, which are again displayed as a countdown, the voting closes and the current ranking is displayed.

- [x] Then, after another limited number of seconds, the cycle begins a new with a new question.
- [x] #55
- [x] #89
- [x] #90

**Comment by a1ps** [comment]
Punkte 2-4 send eig au fertig miinere meinig nach

**Comment by dariokueffer** [comment]
@a1ps yes, gsehni au so, ich schliesses.
