### ISSUE TITLE
US ID12: As the room leader, in the game room screen I want to be able to choose one game mode and one topic of questions from the list of modes and topics respectively so that I can put some variety into the game.

### ISSUE THREAD

**Issue by a1ps** [sopra-fs23-group-12/4Bubbles_Server#12]
- [x] An overview of available game modes is visible

- [x] The game mode overview is a list of selectable items

- [x] The question topics overview is a list of selectable items

- [x] The room leader selection is visible to all the other players in the same room

**Comment by Bluee1Bird** [comment]
proposed additional tasks:
Backend:
a list of available game modes can be accessed

**Comment by dariokueffer** [comment]
@a1ps passt sowyt, chamer schliesse.
