### ISSUE TITLE
US ID13: As a room leader I want to be able to start the countdown that starts the game in order to begin playing.

### ISSUE THREAD

**Issue by a1ps** [sopra-fs23-group-12/4Bubbles_Server#13]
- [x] sopra-fs23-group-12/4Bubbles_Client#40

**AC**
- [x] - [ ] After every setting in the game room (depends on the game mode) has been decided, the game leader can start the game from the game room.

- [x] A countdown starts to let all players know when the game begins.

- [x] When the countdown has ended, the game begins, and the first question is displayed.

**Comment by Bluee1Bird** [comment]
proposed additional tasks:
Backend: 
upon a call form the client, a timer is initialized and started
the timer is comunicated to all players via socketio

**Comment by dariokueffer** [comment]
@a1ps chammer au schliesse, gseht sowyt guet us.
