### ISSUE TITLE
US ID3: As a player, I want to see other players detailed information to decide whether I want to compete with them or not. 

### ISSUE THREAD

**Issue by a1ps** [sopra-fs23-group-12/4Bubbles_Server#15]
- [ ] A user can see a profile page of other players.

- [ ] The profile page provides the following information: username, profile icon, number of games played. number of points, overall ranking.

- [ ] On the profile page there is a button to add that specific player to one's friends list.

**Comment by Bluee1Bird** [comment]
for an indiviual proposed additional tasks:
Backend:
the server allows access to other player's stats
players can be adde to a friendlist (does this really belong in this US?)

**Comment by dariokueffer** [comment]
@MarlenKuehn schliessen als "not planned", ok?

**Comment by MarlenKuehn** [comment]
macht
