### ISSUE TITLE
US ID4: As a player, I want to add other players to my friends list, such that I can directly check out their statistics.  

### ISSUE THREAD

**Issue by a1ps** [sopra-fs23-group-12/4Bubbles_Server#16]
- [ ] The friend list can be accessed and edited (remove or add friends). 

- [ ] By typing in a search field, I can search for other players.

- [ ] With one click I can add a player to my friends list.

- [ ] On the friends list page, I can see all players added to my friends list.

- [ ] On the friends list page, I can click on a certain player and get redirected to their profile page. 

- [ ] A scoreboard for the player’s friends' points is displayed    .

**Comment by Bluee1Bird** [comment]
proposed additional tasks:
Backend:
the server jeeps track of all players and allows searching by name/id
A firendlist can be edited 

what's up with the scoreboard of the firend? Does it display for everyone? Wouldn't it make more sense if you could just visit the profile?

**Comment by a1ps** [comment]
Friendlist hemmer jo killed, drum würdi die US au schlüsse als not planned
