### ISSUE TITLE
US ID16: As a game room leader, I want to be able to define how many questions will have to be answered in one game. So that I can decide the length of the game.

### ISSUE THREAD

**Issue by a1ps** [sopra-fs23-group-12/4Bubbles_Server#17]
- [x] In the game room, only the game room leader has an input field in which he can define the number of questions for the game.

- [x] This number will be displayed for all the other players in the game room.

**Comment by Bluee1Bird** [comment]
proposed additional tasks:
Backend:
the number of questions in a game can be edited by only the game room leader
