### ISSUE TITLE
US ID18: The game can distribute different badges to players, such that the players are motivated to spend more time playing the game.

### ISSUE THREAD

**Issue by a1ps** [sopra-fs23-group-12/4Bubbles_Server#19]
- [ ] A badge consists of an icon and a short text describing the event.

- [ ] For example, a badge can look like this: 🏆 best player of the day.

- [ ] Badges are displayed on the personal profile page and visible for all other logged in users.

- [ ] Other badges could be: “played three games in a row”, “played more than X games in total”, lucky loser, Expert Player, Master in Topic XY, …

**Comment by dariokueffer** [comment]
@MarlenKuehn können wir schliessen als "not planned", oder?

**Comment by MarlenKuehn** [comment]
ja
