### ISSUE TITLE
US ID20: As a player I want to be able to change my vote in order to switch my answer or deceive people.

### ISSUE THREAD

**Issue by a1ps** [sopra-fs23-group-12/4Bubbles_Server#22]
- [x] A bubble shrinks if a vote is changed to a different answer. 

- [x] The vote to a bubble can be changed by clicking on a different one. 

- [x] After the question time is up the bubbles keep their size.

**Comment by Bluee1Bird** [comment]
proposed additional tasks:
Backend:
votes should afford changing

**Comment by dariokueffer** [comment]
@MarlenKuehn das söt eigentlich au laufe, oder?

**Comment by MarlenKuehn** [comment]
das keep their size habe ich anders implementiert, habe es aber im nächsten pull request angepasst
