### ISSUE TITLE
US ID5: As a game room leader, on the game room screen I want to have a list of all available question topics. Such that I can choose one topic from that list

### ISSUE THREAD

**Issue by a1ps** [sopra-fs23-group-12/4Bubbles_Server#4]
- [x] #45
- [x] This information is also visible for all the other players in the room

**Comment by Bluee1Bird** [comment]
proposed additional tasks:
Frontend: 
implement a drop down menu for choosing question topics in the game room view
send the choice to the backend
display the choice of the room leader to the other player's waiting screens
Backend: 
broadcasted to all players in a game room
