### ISSUE TITLE
US ID6: As a game room leader, on the game room screen I want to have a list of all the players in the same room. So that I know who I am playing with.

### ISSUE THREAD

**Issue by a1ps** [sopra-fs23-group-12/4Bubbles_Server#5]
- [x] sopra-fs23-group-12/4Bubbles_Client#11

- [x] This information is also shown to all the other players in the room

**Comment by dariokueffer** [comment]
@a1ps chömmer au schliesse, das midem symbol lömmer weg und de rescht isch guet, oder?
