### ISSUE TITLE
Backend: Build base game logic framework; opening question round and closing after timer is over, accessing current question, increasing points at end.

### ISSUE THREAD

**Issue by fabibert** [sopra-fs23-group-12/4Bubbles_Server#55]
Backend: 
-Build base game logic framework:
    -Question Round class
    -opening question round and closing after timer is over, 
    -accessing current question for this round
    -increasing points at end of round based on voting system evaluation and correct answer

**Comment by a1ps** [comment]
Should have been closed by pull request #80
