### ISSUE TITLE
US ID8: As a player I want to be able to see how the bubbles change their size in order to estimate how many people voted for each answer.

### ISSUE THREAD

**Issue by a1ps** [sopra-fs23-group-12/4Bubbles_Server#7]
- [x] sopra-fs23-group-12/4Bubbles_Client#21
- [x] The number of votes is kept track by the system and displayed in the form of the bubble size. 

- [x] The answer bubbles grow with each vote on it. 

- [x] After the question time is up the bubbles keep their size.
- [x] FrontEnd: Display voting count for each answer in the form of the bubble size. 
- [x] #54

**Comment by Bluee1Bird** [comment]
proposed additional tasks:
Frontend: 
every vote change is sent via a socketio connection to the backend
responses from the backend are displayed in the form of dynamically chaning bubbles

Backend:
calls from the server are processed
a timer is run and communicated to the frontend

**Comment by dariokueffer** [comment]
@MarlenKuehn das isch mit dim PR eigentlich au gschlosse, oder?
