### ISSUE TITLE
US ID10: As a player, I want to be able to see the current overall score of all the players throughout the whole game in order to compare my score to the others and to see my progress relative to the others.

### ISSUE THREAD

**Issue by a1ps** [sopra-fs23-group-12/4Bubbles_Server#9]
- [x] A ranking list is displayed on the right side of the screen. 

- [x] The ranking list shows for each user the username and the current score. The ranking is sorted from first at the top and last at the bottom. 

- [x] After each question the ranking is updated, and the users potentially switch positions.

**Comment by Bluee1Bird** [comment]
proposed additional tasks:
Backend: 
The votes and scores of players is tracked
a ranking is deducted from the player's scores
the ranking is sorted by number of points
the ranking is communicated to the client

**Comment by dariokueffer** [comment]
@a1ps chammer au schliesse, optionals lömmer weg, de rescht passt.
